# ~/.taproot-assets/tapd.conf (Alice)
[Application Options]
network=regtest
tapd-address=0.0.0.0:10029
lnd-address=localhost:10009

[Experimental]
rfq.priceoracleaddress=use_mock_price_oracle_service
rfq.mockoracleassetsperbtc=100000000  # 1 asset = 1 BTC
